version: '3.7'

services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - ../postgres_data_dev:/var/lib/postgresql/data/
      - ../whoosh_index_dev:/home/app/web/whoosh_index
      - ../static_volume_dev:/home/app/web/static_root
      - ../media_volume_dev:/home/app/web/media
    environment:
      - POSTGRES_USER=comohay
      - POSTGRES_PASSWORD=comohay
      - POSTGRES_DB=comohay_dev
    ports:
      - 5433:5432
  redis:
    restart: always
    image: redis:5.0
    expose:
      - "6379"

volumes:
  postgres_data: