version: '3.7'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn comohay.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ../whoosh_index:/home/app/web/whoosh_index
      - ../static_volume:/home/app/web/static_root
      - ../media_volume:/home/app/web/media
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - ../static_volume:/home/app/web/static_root
      - ../media_volume:/home/app/web/media
    depends_on:
      - web

  db:
    image: postgres:12.0-alpine
    volumes:
      - ../postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod

volumes:
  postgres_data: